name: Frontend CI

on:
  push:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: [self-hosted, self-run]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'  
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Restart Frontend Server
      run: pm2 restart recruit-inn-fe