const stackIcons = [
  { name: "Adobe", icon: "adobe" },
  { name: "Adobe After Effect", icon: "ae" },
  { name: "Adobe Photoshop", icon: "ps" },
  { name: "Adobe Lightroom", icon: "lightroom" },
  { name: "Adobe Illustrator", icon: "ai" },
  { name: "Adobe Indesign", icon: "id" },
  { name: "Affinity", icon: "affinity" },
  { name: "Affinity Designer", icon: "affinitydesigner" },
  { name: "Affinity Photo", icon: "affinityphoto" },
  { name: "Affinity Publisher", icon: "affinitypublisher" },
  { name: "Airtable", icon: "airtable" },
  { name: "airtable", icon: "airtable" },
  { name: "alacritty", icon: "alacritty" },
  { name: "algolia", icon: "algolia" },
  { name: "algorand", icon: "algorand" },
  { name: "alpinejs", icon: "alpinejs" },
  { name: "amp", icon: "amp" },
  { name: "amznwebserv", icon: "amznwebserv" },
  { name: "analytics", icon: "analytics" },
  { name: "android", icon: "android" },
  { name: "angular", icon: "angular" },
  { name: "angular17", icon: "angular17" },
  { name: "antd", icon: "antd" },
  { name: "apache", icon: "apache" },
  { name: "appwriter", icon: "appwriter" },
  { name: "arc", icon: "arc" },
  { name: "astro", icon: "astro" },
  { name: "atlassian", icon: "atlassian" },
  { name: "atom", icon: "atom" },
  { name: "auth0", icon: "auth0" },
  { name: "avajs", icon: "avajs" },
  { name: "aws", icon: "aws" },
  { name: "axiom", icon: "axiom" },
  { name: "axm", icon: "axm" },
  { name: "axure", icon: "axure" },
  { name: "azure", icon: "azure" },
  { name: "babel", icon: "babel" },
  { name: "backbonejs", icon: "backbonejs" },
  { name: "bash", icon: "bash" },
  { name: "bitbucket", icon: "bitbucket" },
  { name: "bitnami", icon: "bitnami" },
  { name: "blueprintjs", icon: "blueprintjs" },
  { name: "bootstrap4", icon: "bootstrap4" },
  { name: "bootstrap5", icon: "bootstrap5" },
  { name: "brave", icon: "brave" },
  { name: "bulmaui", icon: "bulmaui" },
  { name: "bunjs", icon: "bunjs" },
  { name: "c++", icon: "c++" },
  { name: "cakephp", icon: "cakephp" },
  { name: "canva", icon: "canva" },
  { name: "cassandradb", icon: "cassandradb" },
  { name: "chakraui", icon: "chakraui" },
  { name: "chrome", icon: "chrome" },
  { name: "chromium", icon: "chromium" },
  { name: "circleci", icon: "circleci" },
  { name: "clickhouse", icon: "clickhouse" },
  { name: "clojure", icon: "clojure" },
  { name: "cloudflare", icon: "cloudflare" },
  { name: "cloudinary", icon: "cloudinary" },
  { name: "codefresh", icon: "codefresh" },
  { name: "codeigniter", icon: "codeigniter" },
  { name: "copilotgithub", icon: "copilotgithub" },
  { name: "copilotms", icon: "copilotms" },
  { name: "crystal", icon: "crystal" },
  { name: "csharp", icon: "csharp" },
  { name: "css3", icon: "css3" },
  { name: "cypress", icon: "cypress" },
  { name: "dart", icon: "dart" },
  { name: "datadog", icon: "datadog" },
  { name: "deno", icon: "deno" },
  { name: "digitalocean", icon: "digitalocean" },
  { name: "django", icon: "django" },
  { name: "dlang", icon: "dlang" },
  { name: "docker", icon: "docker" },
  { name: "docusaurus", icon: "docusaurus" },
  { name: "dovetail", icon: "dovetail" },
  { name: "ec2", icon: "ec2" },
  { name: "edge", icon: "edge" },
  { name: "elastic", icon: "elastic" },
  { name: "electron", icon: "electron" },
  { name: "elementui", icon: "elementui" },
  { name: "elixir", icon: "elixir" },
  { name: "ember", icon: "ember" },
  { name: "erlang", icon: "erlang" },
  { name: "esbuild", icon: "esbuild" },
  { name: "eslint", icon: "eslint" },
  { name: "faunadb", icon: "faunadb" },
  { name: "figma", icon: "figma" },
  { name: "firebase", icon: "firebase" },
  { name: "firefox", icon: "firefox" },
  { name: "flask", icon: "flask" },
  { name: "flutter", icon: "flutter" },
  { name: "flyio", icon: "flyio" },
  { name: "framer", icon: "framer" },
  { name: "gatsby", icon: "gatsby" },
  { name: "gcloud", icon: "gcloud" },
  { name: "git", icon: "git" },
  { name: "github", icon: "github" },
  { name: "gitlab", icon: "gitlab" },
  { name: "go", icon: "go" },
  { name: "grafana", icon: "grafana" },
  { name: "grafbase", icon: "grafbase" },
  { name: "graphite", icon: "graphite" },
  { name: "graphql", icon: "graphql" },
  { name: "gridsome", icon: "gridsome" },
  { name: "gruntjs", icon: "gruntjs" },
  { name: "gulp", icon: "gulp" },
  { name: "haskell", icon: "haskell" },
  { name: "headlessui", icon: "headlessui" },
  { name: "heroku", icon: "heroku" },
  { name: "hexo", icon: "hexo" },
  { name: "hhvm", icon: "hhvm" },
  { name: "homebrew", icon: "homebrew" },
  { name: "hotjar", icon: "hotjar" },
  { name: "html5", icon: "html5" },
  { name: "hyper", icon: "hyper" },
  { name: "hyper2", icon: "hyper2" },
  { name: "i18next", icon: "i18next" },
  { name: "Internet Explorer", icon: "ie" },
  { name: "inkspace", icon: "inkspace" },
  { name: "insomnia", icon: "insomnia" },
  { name: "invision", icon: "invision" },
  { name: "ionic", icon: "ionic" },
  { name: "jamstack", icon: "jamstack" },
  { name: "java", icon: "java" },
  { name: "jest", icon: "jest" },
  { name: "jira", icon: "jira" },
  { name: "jquery", icon: "jquery" },
  { name: "javascript", icon: "js" },
  { name: "jslint", icon: "jslint" },
  { name: "json", icon: "json" },
  { name: "kibana", icon: "kibana" },
  { name: "kotlin", icon: "kotlin" },
  { name: "kubernetes", icon: "kubernetes" },
  { name: "laravel", icon: "laravel" },
  { name: "less", icon: "less" },
  { name: "linux", icon: "linux" },
  { name: "lit", icon: "lit" },
  { name: "liveblocks", icon: "liveblocks" },
  { name: "logrocket", icon: "logrocket" },
  { name: "lokalise", icon: "lokalise" },
  { name: "lua", icon: "lua" },
  { name: "lunacy", icon: "lunacy" },
  { name: "mariadb", icon: "mariadb" },
  { name: "marionette", icon: "marionette" },
  { name: "markdown", icon: "markdown" },
  { name: "materialui", icon: "materialui" },
  { name: "meta", icon: "meta" },
  { name: "microsoft", icon: "microsoft" },
  { name: "miro", icon: "miro" },
  { name: "mochajs", icon: "mochajs" },
  { name: "mongodb", icon: "mongodb" },
  { name: "mozilla", icon: "mozilla" },
  { name: "mysql", icon: "mysql" },
  { name: "neovim", icon: "neovim" },
  { name: "nestjs", icon: "nestjs2" },
  { name: "netlify", icon: "netlify2" },
  { name: "nextjs", icon: "nextjs2" },
  { name: "nim", icon: "nim" },
  { name: "nitro", icon: "nitro" },
  { name: "nodejs", icon: "nodejs" },
  { name: "npm", icon: "npm" },
  { name: "npm2", icon: "npm2" },
  { name: "nuxtjs", icon: "nuxtjs" },
  { name: "ocaml", icon: "ocaml" },
  { name: "onedrive", icon: "onedrive" },
  { name: "openai", icon: "openai" },
  { name: "opera", icon: "opera" },
  { name: "oracle", icon: "oracle" },
  { name: "pandacss", icon: "pandacss" },
  { name: "php", icon: "php" },
  { name: "pinia", icon: "pinia" },
  { name: "pixijs", icon: "pixijs" },
  { name: "playwright", icon: "playwright" },
  { name: "postgresql", icon: "postgresql" },
  { name: "postman", icon: "postman" },
  { name: "powershell", icon: "powershell" },
  { name: "preact", icon: "preact" },
  { name: "presto", icon: "presto" },
  { name: "Prettier", icon: "prettier" },
  { name: "prisma", icon: "prisma" },
  { name: "pugjs", icon: "pugjs" },
  { name: "Progressive Web Apps", icon: "pwa" },
  { name: "Pytorch", icon: "pytorch" },
  { name: "Pytorch3d", icon: "pytorch3d" },
  { name: "Qwik", icon: "qwik" },
  { name: "Redixui", icon: "redixui" },
  { name: "Rails", icon: "rails" },
  { name: "Railway", icon: "railway" },
  { name: "Reactjs", icon: "reactjs" },
  { name: "Reactquery", icon: "reactquery" },
  { name: "Reactrouter", icon: "reactrouter" },
  { name: "Redhat", icon: "redhat" },
  { name: "Redis", icon: "redis" },
  { name: "Redux", icon: "redux" },
  { name: "Reduxsaga", icon: "reduxsaga" },
  { name: "Render", icon: "render" },
  { name: "esend", icon: "resend" },
  { name: "Rollup", icon: "rollup" },
  { name: "Ruby", icon: "ruby" },
  { name: "Rust", icon: "rust" },
  { name: "Safari", icon: "safari" },
  { name: "Sass", icon: "sass" },
  { name: "Scala", icon: "scala" },
  { name: "Semanticui", icon: "semanticui" },
  { name: "Serverless", icon: "serverless" },
  { name: "Shadcnui", icon: "shadcnui" },
  { name: "Sketch", icon: "sketch" },
  { name: "Sketch2", icon: "sketch2" },
  { name: "Slack", icon: "slack" },
  { name: "Solidity", icon: "solidity" },
  { name: "Solidjs", icon: "solidjs" },
  { name: "Spring", icon: "spring" },
  { name: "Storyblok", icon: "storyblok" },
  { name: "Storybook", icon: "storybook" },
  { name: "Strada", icon: "strada" },
  { name: "Stream", icon: "stream" },
  { name: "Stylelint", icon: "stylelint" },
  { name: "Sublime", icon: "sublime" },
  { name: "Supabase", icon: "supabase" },
  { name: "sveltejs", icon: "sveltejs" },
  { name: "swagger", icon: "swagger" },
  { name: "swift", icon: "swift" },
  { name: "tailwindcss", icon: "tailwindcss" },
  { name: "threejs", icon: "threejs" },
  { name: "tinyhttp", icon: "tinyhttp" },
  { name: "tRPC", icon: "trpc" },
  { name: "Typescript", icon: "typescript" },
  { name: "Ubuntu", icon: "ubuntu" },
  { name: "UnJS", icon: "unjs" },
  { name: "Vim", icon: "vim" },
  { name: "Visual Basic", icon: "visualbasic" },
  { name: "Vitejs", icon: "vitejs" },
  { name: "Vitest", icon: "vitest" },
  { name: "VScode", icon: "vscode" },
  { name: "Vuejs", icon: "vuejs" },
  { name: "WebAssembly", icon: "webassembly" },
  { name: "Webpack", icon: "webpack" },
  { name: "Wordpress", icon: "wordpress" },
  { name: "Xamarin", icon: "xamarin" },
  { name: "Experience Design", icon: "xd" },
  { name: "Yoga", icon: "yoga" },
  { name: "Zod", icon: "zod" },
];

export default function handler(req, res) {
  const { query } = req.body;

  console.log(req.body);

  if (!query) {
    // If query is not provided
    return res.status(400).json({ error: "Query is required" });
  }

  // Filter
  const filteredIcons = stackIcons.filter((icon) =>
    icon.name.toLowerCase().includes(query.toLowerCase())
  );

  console.log(filteredIcons);

  // Return
  res.status(200).json(filteredIcons);
}
