name: Frontend CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Manually Trigger Backend Workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Trigger the backend workflow
          response=$(curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${GITHUB_TOKEN}" \
            https://api.github.com/repos/sohaibabbasi26/events-app-backend/actions/workflows/backend.yml/dispatches \
            -d '{"ref":"main"}')
          echo "Workflow dispatched. Response: $response"

      - name: Restart Frontend Server
        run: pm2 restart recruit-inn-fe-frontend
