name: Frontend CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: self-run

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'  # Choose the Node.js version you want to use
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build  # Adjust this command based on your project setup
